server.port=8082
spring.application.name=inventory-service

eureka.client.service-url.defaultZone=http://eureka:password@localhost:8761/eureka/
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8085/realms/spring-boot-microservices-realm


spring.kafka.bootstrap-servers=localhost:9092
#spring.kafka.properties.schema.registry.url=http://localhost:8081


#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=io.confluent.kafka.serializers.json.KafkaJsonSchemaSerializer
#spring.kafka.producer.properties.auto.register.schemas=true

#spring.kafka.producer.properties.enable.idempotence=true
#spring.kafka.producer.properties.acks=all
#spring.kafka.producer.properties.retries=10
#spring.kafka.producer.properties.max.in.flight.requests.per.connection=5

#logging.level.org.apache.kafka.streams=INFO
#logging.level.org.springframework.kafka=INFO


logging.level.root=ERROR

# KAFKA STREAMS CONFIG
spring.kafka.streams.properties.application.id=inventory-streams-v11
#spring.kafka.streams.properties.state.dir=./.kafka-streams
spring.kafka.streams.properties.application.server=localhost:8082
spring.kafka.streams.properties.processing.guarantee=exactly_once_v2
spring.kafka.streams.properties.default.key.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.default.value.serde=org.apache.kafka.common.serialization.Serdes$StringSerde
spring.kafka.streams.properties.consumer.auto.offset.reset=earliest

spring.kafka.streams.properties.num.stream.threads = 4

#spring.kafka.listener.ack-mode=batch

# Cần mở rộng đường ống để không làm nghẽn Order Service.
server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20

# Hàng đợi chờ: 2000 (Để đồng bộ với các service khác)
server.tomcat.accept-count=2000
server.tomcat.max-connections=8192
server.tomcat.connection-timeout=20000

# Tối ưu batching cho Inventory events
#spring.kafka.producer.properties.linger.ms=5
#spring.kafka.producer.properties.batch.size=32768
#spring.kafka.producer.properties.compression.type=snappy

spring.kafka.streams.properties.state.dir=./data/kafka-streams

# thêm mới
# Kafka consumer cho reservation commands
#spring.kafka.consumer.group-id=inventory-command-group
#spring.kafka.consumer.auto-offset-reset=earliest

# LSF quota
lsf.quota.enabled=true
lsf.quota.store=REDIS
#lsf.quota.default-hold-seconds=120
lsf.quota.keep-alive-seconds=86400
#allow-release-confirmed=false: đã confirm rồi thì không cho release ngược
lsf.quota.allow-release-confirmed=false
lsf.quota.metrics-enabled=true

spring.data.redis.host=localhost
spring.data.redis.port=6379

#new
lsf.kafka.bootstrap-servers=localhost:9092
lsf.kafka.schema-registry-url=http://localhost:8081
lsf.kafka.consumer.group-id=inventory-command-group
lsf.kafka.consumer.auto-offset-reset=earliest
lsf.kafka.consumer.batch=false
lsf.kafka.consumer.json-value-type=com.myorg.lsf.contracts.core.envelope.EventEnvelope

lsf.kafka.producer.acks=all
lsf.kafka.producer.idempotence=true
lsf.kafka.producer.retries=10
lsf.kafka.producer.max-in-flight=5
lsf.kafka.producer.linger-ms=5
lsf.kafka.producer.batch-size=32768
lsf.kafka.producer.compression=snappy

#observability
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

lsf.observability.enabled=true
lsf.observability.mdc-enabled=true
lsf.observability.metrics-enabled=true
lsf.observability.tracing-enabled=true

lsf.observability.tag-topic=true
lsf.observability.tag-event-type=true
lsf.observability.tag-outcome=true
lsf.observability.tag-event-id=false
management.tracing.sampling.probability=1.0

#logging.level.com.myexampleproject.inventoryservice.service.InventoryQuotaService=INFO
#logging.level.com.myexampleproject.inventoryservice.messaging.InventoryReservationCommandListener=INFO
logging.level.org.apache.kafka=ERROR

lsf.eventing.consume-topics[0]=inventory-reservation-confirm-envelope-topic
lsf.eventing.consume-topics[1]=inventory-reservation-release-envelope-topic
lsf.eventing.ignore-unknown-event-type=true
lsf.eventing.idempotency.enabled=true
lsf.eventing.idempotency.store=memory
lsf.eventing.idempotency.key-prefix=lsf:inventory:idemp:{groupId}:

app.inventory.legacy-reservation-listener.enabled=false

lsf.quota.default-hold-seconds=900